// <auto-generated />
namespace CDYNews.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_Page : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Page));
        
        string IMigrationMetadata.Id
        {
            get { return "201801170700523_update_Page"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
